// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import type { LocalizedString } from 'typesafe-i18n';

export type BaseLocale = 'en';

export type Locales = 'en' | 'jp';

export type Translation = {
	/**
	 * Reminders
	 */
	TITLE: string;
	/**
	 * Reminder Description
	 */
	DESCRIPTION: string;
	/**
	 * Reminder URL
	 */
	URL: string;
	/**
	 * Use Dark Mode
	 */
	DARK: string;
	/**
	 * Use Light Mode
	 */
	LIGHT: string;
	/**
	 * Calendar
	 */
	CALENDAR: string;
	/**
	 * Add Reminder
	 */
	ADD: string;
	/**
	 * Item
	 */
	ITEM: string;
	/**
	 * No reminders here
	 */
	NONE: string;
	/**
	 * You have no more reminders
	 */
	CLEAR: string;
	/**
	 * Create Reminder Group
	 */
	CREATE_GROUP: string;
	/**
	 * Create Group
	 */
	CREATE_GROUP_BTN: string;
	/**
	 * Expired
	 */
	EXPIRED: string;
	/**
	 * Link
	 */
	LINK: string;
	/**
	 * Update Time
	 */
	UPDATE_TIME: string;
	/**
	 * Edit
	 */
	EDIT: string;
	/**
	 * Save
	 */
	SAVE: string;
	/**
	 * Delete
	 */
	DELETE: string;
	/**
	 * Cancel
	 */
	CANCEL: string;
	/**
	 * Skip Month and Year Selection
	 */
	SKIP_MONTHS: string;
	/**
	 * Skip Date Selection
	 */
	SKIP_DAYS: string;
	/**
	 * Month and Year Selection
	 */
	MONTH_YEAR_SELECTION: string;
	/**
	 * Date Selection
	 */
	DATE_SELECTION: string;
	/**
	 * Time Selection
	 */
	TIME_SELECTION: string;
	/**
	 * hour
	 */
	HOUR: string;
	/**
	 * minute
	 */
	MINUTE: string;
	/**
	 * Select Time
	 */
	SELECT_TIME: string;
	/**
	 * Sun
	 */
	SUN: string;
	/**
	 * Mon
	 */
	MON: string;
	/**
	 * Tue
	 */
	TUE: string;
	/**
	 * Wed
	 */
	WED: string;
	/**
	 * Thu
	 */
	THU: string;
	/**
	 * Fri
	 */
	FRI: string;
	/**
	 * Sat
	 */
	SAT: string;
	/**
	 * Jan
	 */
	JAN: string;
	/**
	 * Feb
	 */
	FEB: string;
	/**
	 * Mar
	 */
	MAR: string;
	/**
	 * Apr
	 */
	APR: string;
	/**
	 * May
	 */
	MAY: string;
	/**
	 * Jun
	 */
	JUN: string;
	/**
	 * Jul
	 */
	JUL: string;
	/**
	 * Aug
	 */
	AUG: string;
	/**
	 * Sep
	 */
	SEP: string;
	/**
	 * Oct
	 */
	OCT: string;
	/**
	 * Nov
	 */
	NOV: string;
	/**
	 * Dec
	 */
	DEC: string;
	/**
	 * dates would be in the past
	 */
	DATE_IN_PAST: string;
	/**
	 * Selected
	 */
	SELECTED: string;
	/**
	 * Recur Weekly
	 */
	RECUR: string;
	/**
	 * English
	 */
	EN: string;
	/**
	 * 日本語
	 */
	JP: string;
};

export type TranslationFunctions = {
	/**
	 * Reminders
	 */
	TITLE: () => LocalizedString;
	/**
	 * Reminder Description
	 */
	DESCRIPTION: () => LocalizedString;
	/**
	 * Reminder URL
	 */
	URL: () => LocalizedString;
	/**
	 * Use Dark Mode
	 */
	DARK: () => LocalizedString;
	/**
	 * Use Light Mode
	 */
	LIGHT: () => LocalizedString;
	/**
	 * Calendar
	 */
	CALENDAR: () => LocalizedString;
	/**
	 * Add Reminder
	 */
	ADD: () => LocalizedString;
	/**
	 * Item
	 */
	ITEM: () => LocalizedString;
	/**
	 * No reminders here
	 */
	NONE: () => LocalizedString;
	/**
	 * You have no more reminders
	 */
	CLEAR: () => LocalizedString;
	/**
	 * Create Reminder Group
	 */
	CREATE_GROUP: () => LocalizedString;
	/**
	 * Create Group
	 */
	CREATE_GROUP_BTN: () => LocalizedString;
	/**
	 * Expired
	 */
	EXPIRED: () => LocalizedString;
	/**
	 * Link
	 */
	LINK: () => LocalizedString;
	/**
	 * Update Time
	 */
	UPDATE_TIME: () => LocalizedString;
	/**
	 * Edit
	 */
	EDIT: () => LocalizedString;
	/**
	 * Save
	 */
	SAVE: () => LocalizedString;
	/**
	 * Delete
	 */
	DELETE: () => LocalizedString;
	/**
	 * Cancel
	 */
	CANCEL: () => LocalizedString;
	/**
	 * Skip Month and Year Selection
	 */
	SKIP_MONTHS: () => LocalizedString;
	/**
	 * Skip Date Selection
	 */
	SKIP_DAYS: () => LocalizedString;
	/**
	 * Month and Year Selection
	 */
	MONTH_YEAR_SELECTION: () => LocalizedString;
	/**
	 * Date Selection
	 */
	DATE_SELECTION: () => LocalizedString;
	/**
	 * Time Selection
	 */
	TIME_SELECTION: () => LocalizedString;
	/**
	 * hour
	 */
	HOUR: () => LocalizedString;
	/**
	 * minute
	 */
	MINUTE: () => LocalizedString;
	/**
	 * Select Time
	 */
	SELECT_TIME: () => LocalizedString;
	/**
	 * Sun
	 */
	SUN: () => LocalizedString;
	/**
	 * Mon
	 */
	MON: () => LocalizedString;
	/**
	 * Tue
	 */
	TUE: () => LocalizedString;
	/**
	 * Wed
	 */
	WED: () => LocalizedString;
	/**
	 * Thu
	 */
	THU: () => LocalizedString;
	/**
	 * Fri
	 */
	FRI: () => LocalizedString;
	/**
	 * Sat
	 */
	SAT: () => LocalizedString;
	/**
	 * Jan
	 */
	JAN: () => LocalizedString;
	/**
	 * Feb
	 */
	FEB: () => LocalizedString;
	/**
	 * Mar
	 */
	MAR: () => LocalizedString;
	/**
	 * Apr
	 */
	APR: () => LocalizedString;
	/**
	 * May
	 */
	MAY: () => LocalizedString;
	/**
	 * Jun
	 */
	JUN: () => LocalizedString;
	/**
	 * Jul
	 */
	JUL: () => LocalizedString;
	/**
	 * Aug
	 */
	AUG: () => LocalizedString;
	/**
	 * Sep
	 */
	SEP: () => LocalizedString;
	/**
	 * Oct
	 */
	OCT: () => LocalizedString;
	/**
	 * Nov
	 */
	NOV: () => LocalizedString;
	/**
	 * Dec
	 */
	DEC: () => LocalizedString;
	/**
	 * dates would be in the past
	 */
	DATE_IN_PAST: () => LocalizedString;
	/**
	 * Selected
	 */
	SELECTED: () => LocalizedString;
	/**
	 * Recur Weekly
	 */
	RECUR: () => LocalizedString;
	/**
	 * English
	 */
	EN: () => LocalizedString;
	/**
	 * 日本語
	 */
	JP: () => LocalizedString;
};

export type Formatters = {};
